import React,{useEffect,useState}from"react";
import{Bell,BellRing,Check,LoaderCircle,X}from"lucide-react";
type PushState="checking"|"unsupported"|"denied"|"off"|"on"|"busy"|"error";
function encodeKey(value:string):Uint8Array{const padded=value.replace(/-/g,"+").replace(/_/g,"/")+"=".repeat((4-value.length%4)%4);return Uint8Array.from(atob(padded),c=>c.charCodeAt(0))}
export default function PushNotifications(){const[state,setState]=useState<PushState>("checking"),[hidden,setHidden]=useState(false),[message,setMessage]=useState("");
useEffect(()=>{let alive=true;const check=async()=>{if(!("serviceWorker"in navigator)||!("PushManager"in window)||!("Notification"in window)){if(alive)setState("unsupported");return}if(Notification.permission==="denied"){if(alive)setState("denied");return}try{const reg=await navigator.serviceWorker.ready,sub=await reg.pushManager.getSubscription();if(alive)setState(sub?"on":"off")}catch{if(alive)setState("off")}};void check();return()=>{alive=false}},[]);
const toggle=async()=>{setState("busy");setMessage("");try{if(!("serviceWorker"in navigator)||!("PushManager"in window))throw Error("Push notifications aren't supported by this browser.");const reg=await navigator.serviceWorker.ready,existing=await reg.pushManager.getSubscription();if(existing){const r=await fetch("/api/custom-message",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"PUSH_UNSUBSCRIBE",subscription:existing.toJSON()}),credentials:"same-origin"});if(!r.ok)throw Error((await r.json().catch(()=>({}))).error||"Could not disable notifications.");await existing.unsubscribe();setState("off");setMessage("Notifications disabled.");return}const permission=Notification.permission==="default"?await Notification.requestPermission():Notification.permission;if(permission!=="granted"){setState(permission==="denied"?"denied":"off");throw Error("Allow notifications in your browser settings to enable alerts.")}const kr=await fetch("/api/custom-message",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"PUSH_PUBLIC_KEY"}),credentials:"same-origin",cache:"no-store"}),kd=await kr.json().catch(()=>({}));if(!kr.ok||!kd.publicKey)throw Error(kd.error||"Push notifications aren't configured yet.");const sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:encodeKey(kd.publicKey)});const r=await fetch("/api/custom-message",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"PUSH_SUBSCRIBE",subscription:sub.toJSON()}),credentials:"same-origin"});if(!r.ok){await sub.unsubscribe().catch(()=>{});throw Error((await r.json().catch(()=>({}))).error||"Could not enable notifications.")}setState("on");setMessage("You'll receive new gift-code and developer message alerts.")}catch(e){setState("error");setMessage(e instanceof Error?e.message:"Could not update notification settings.")}};
if(["unsupported","denied","checking"].includes(state)||hidden)return null;
return <aside style={{position:"fixed",zIndex:30,right:16,bottom:"max(16px, env(safe-area-inset-bottom))",width:"min(340px, calc(100vw - 32px))",padding:16,border:"1px solid var(--border, #303642)",borderRadius:16,background:"var(--panel, #151922)",color:"var(--text, #f4f6fb)",boxShadow:"0 12px 36px #0005",fontSize:14}}><button type="button" onClick={()=>setHidden(true)} aria-label="Dismiss notification settings" style={{float:"right",background:"transparent",color:"inherit",border:0,padding:4}}><X size={16}/></button><div style={{display:"flex",gap:10,alignItems:"center",marginBottom:8}}>{state==="on"?<BellRing size={20}/>:<Bell size={20}/>}<strong>Push notifications</strong></div><p style={{margin:"0 0 12px",opacity:.8,lineHeight:1.45}}>Only custom developer messages and newly available gift codes. No redemption or account alerts.</p><button type="button" disabled={state==="busy"} onClick={()=>void toggle()} style={{display:"flex",gap:8,alignItems:"center",justifyContent:"center",width:"100%",padding:"10px 12px",borderRadius:10,border:0,fontWeight:650,background:state==="on"?"#303846":"#6679ff",color:"white",opacity:state==="busy" ? 0.7 : 1}}>{state==="busy"?<LoaderCircle size={16} className="spin"/>:state==="on"?<Check size={16}/>:<Bell size={16}/>} {state==="on"?"Disable notifications":"Enable notifications"}</button>{message&&<p role="status" style={{margin:"10px 0 0",lineHeight:1.4}}>{message}</p>}</aside>}
