import webpush from "web-push";
const BASE=process.env.SUPABASE_URL||"https://wocxvtptqapietlteshr.supabase.co",KEY=process.env.SUPABASE_SERVICE_ROLE_KEY||process.env.SUPABASE_SECRET_KEY,PUBLIC_KEY=process.env.WEB_PUSH_VAPID_PUBLIC_KEY||"",PRIVATE_KEY=process.env.WEB_PUSH_VAPID_PRIVATE_KEY||"",SUBJECT=process.env.WEB_PUSH_VAPID_SUBJECT||"mailto:admin@kingshot-autoredeemer.vercel.app";
export function pushIsConfigured():boolean{return Boolean(KEY&&PUBLIC_KEY&&PRIVATE_KEY)}
export function getPushPublicKey():string{return PUBLIC_KEY}
async function db(path:string,init:RequestInit={}):Promise<Response>{if(!KEY)throw Error("Push storage is not configured.");return fetch(BASE+"/rest/v1/"+path,{...init,headers:{apikey:KEY,authorization:"Bearer "+KEY,"content-type":"application/json",...(init.headers||{})},signal:AbortSignal.timeout(10000)})}
let vapidReady=false;
function configureVapid():void{if(!pushIsConfigured())throw Error("Web Push VAPID keys are not configured.");if(!vapidReady){webpush.setVapidDetails(SUBJECT,PUBLIC_KEY,PRIVATE_KEY);vapidReady=true}}
export interface PushPayload{title:string;body:string;url?:string;tag:string}
export async function broadcastPush(payload:PushPayload):Promise<{sent:number;removed:number;failed:number}>{
 configureVapid();const response=await db("kingshot_push_subscriptions?select=id,endpoint,p256dh,auth");if(!response.ok)throw Error("Could not load push subscriptions ("+response.status+").");
 const rows=await response.json() as Array<{id:number;endpoint:string;p256dh:string;auth:string}>;let sent=0,removed=0,failed=0;
 const notification=JSON.stringify({title:String(payload.title).slice(0,100),body:String(payload.body).slice(0,220),url:payload.url&&payload.url.startsWith("/")&&!payload.url.startsWith("//")?payload.url:"/",tag:String(payload.tag).slice(0,100)});
 for(const row of rows){try{await webpush.sendNotification({endpoint:row.endpoint,keys:{p256dh:row.p256dh,auth:row.auth}},notification,{TTL:86400});sent++}catch(error){const status=Number((error as {statusCode?:number})?.statusCode||0);if(status===404||status===410){const deleted=await db("kingshot_push_subscriptions?id=eq."+encodeURIComponent(String(row.id)),{method:"DELETE"});if(deleted.ok)removed++;else failed++}else failed++}}
 return{sent,removed,failed}
}
export async function savePushSubscription(value:unknown):Promise<void>{const item=value as{endpoint?:unknown;keys?:{p256dh?:unknown;auth?:unknown}},endpoint=String(item?.endpoint||""),p256dh=String(item?.keys?.p256dh||""),auth=String(item?.keys?.auth||"");let url:URL;try{url=new URL(endpoint)}catch{throw Error("Invalid push endpoint.")}if(url.protocol!=="https:"||endpoint.length>2048||p256dh.length>256||auth.length>256||!p256dh||!auth)throw Error("Invalid push subscription.");const r=await db("kingshot_push_subscriptions?on_conflict=endpoint",{method:"POST",headers:{Prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify({endpoint,p256dh,auth,last_seen_at:new Date().toISOString()})});if(!r.ok)throw Error("Could not save push subscription ("+r.status+").")}
export async function removePushSubscription(value:unknown):Promise<void>{const endpoint=String((value as{endpoint?:unknown})?.endpoint||"");let url:URL;try{url=new URL(endpoint)}catch{throw Error("Invalid push endpoint.")}if(url.protocol!=="https:"||endpoint.length>2048)throw Error("Invalid push endpoint.");const r=await db("kingshot_push_subscriptions?endpoint=eq."+encodeURIComponent(endpoint),{method:"DELETE"});if(!r.ok)throw Error("Could not remove push subscription ("+r.status+").")}
