import React,{useCallback,useEffect,useState}from"react";
import{Activity,AlertTriangle,CheckCircle,Clock,Gift,LogOut,Plus,RefreshCw,RotateCcw,ShieldCheck,Trash2,LoaderCircle}from"lucide-react";
const api=(body)=>fetch("/api/custom-message",{method:"POST",credentials:"same-origin",headers:{"content-type":"application/json"},body:JSON.stringify(body),cache:"no-store"}).then(async r=>{const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Request failed.");return d});
const date=v=>v?new Date(v).toLocaleString(): "—";
export default function GiftCodesApp(){
 const[passkey,setPasskey]=useState(""),[authed,setAuthed]=useState(false),[checking,setChecking]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[codes,setCodes]=useState([]),[code,setCode]=useState(""),[expires,setExpires]=useState(""),[filter,setFilter]=useState("all");
 const load=useCallback(async()=>{setBusy(true);setError("");try{const d=await api({action:"GIFT_CODE_LIST"});setCodes(d.codes||[])}catch(e){setError(e.message)}finally{setBusy(false)}},[]);
 useEffect(()=>{let live=true;api({action:"CHECK"}).then(()=>{if(live){setAuthed(true);return load()}}).catch(()=>{}).finally(()=>{if(live)setChecking(false)});return()=>{live=false}},[load]);
 const run=async(action,extra={})=>{setBusy(true);setError("");setNotice("");try{const d=await api({action,...extra});if(action==="LOGOUT"){setAuthed(false);setPasskey("");setCodes([])}else if(action==="GIFT_CODE_ADD"){setCode("");setExpires("");setNotice(d.restored?"Code reactivated.":"Code added.");await load()}else if(action==="GIFT_CODE_UPDATE"){setNotice("Gift code updated.");await load()}else if(action==="GIFT_CODE_DELETE"){setNotice("Code removed from the active pool.");await load()}else if(action==="GIFT_CODE_LIST"){setCodes(d.codes||[])}else{setNotice(action==="TRIGGER_KINGDOM_VALIDATION"?"Kingdom validation finished.":"Auto-redeem worker run finished.");setNotice(JSON.stringify(d.result||d));}}catch(e){setError(e.message)}finally{setBusy(false)}};
 const login=async e=>{e.preventDefault();setBusy(true);setError("");try{await api({action:"LOGIN",passkey});setAuthed(true);setPasskey("");await load()}catch(e){setError(e.message)}finally{setBusy(false)}};
 const visible=codes.filter(c=>filter==="all"||(filter==="active"?c.active:c.active===false));
 const activeCount=codes.filter(c=>c.active&&(!c.expires_at||Date.parse(c.expires_at)>Date.now())).length;
 const shell={minHeight:"100vh",background:"#090b10",color:"#e9eaf0",fontFamily:"system-ui,sans-serif",padding:"clamp(16px,4vw,36px)",boxSizing:"border-box"};
 const panel={background:"#10131a",border:"1px solid #272c37",borderRadius:16,padding:18};
 const btn={display:"inline-flex",alignItems:"center",justifyContent:"center",gap:7,minHeight:38,padding:"9px 12px",border:"1px solid #303744",borderRadius:9,background:"#171c25",color:"#d9dde7",fontWeight:750,fontSize:12,cursor:"pointer"};
 const field={width:"100%",boxSizing:"border-box",padding:"11px 12px",border:"1px solid #303744",borderRadius:9,background:"#0b0e14",color:"#f0f1f5",fontSize:13};
 if(checking)return <main style={{...shell,display:"grid",placeItems:"center"}}>Checking admin session…</main>;
 if(!authed)return <main style={{...shell,display:"grid",placeItems:"center"}}><form onSubmit={login} style={{...panel,width:"min(100%,380px)",boxSizing:"border-box"}}><div style={{display:"flex",alignItems:"center",gap:10,marginBottom:18}}><span style={{display:"grid",placeItems:"center",width:42,height:42,borderRadius:12,background:"#242036",color:"#c6b5ff"}}><ShieldCheck size={22}/></span><div><small style={{color:"#9d8bd6",fontWeight:800,letterSpacing:".12em"}}>ADMIN ACCESS</small><h1 style={{fontSize:22,margin:"3px 0 0"}}>Gift code control</h1></div></div><p style={{color:"#8e95a4",fontSize:12,lineHeight:1.6}}>Use the same admin passkey as the Discord custom-message page.</p><label style={{display:"block",fontSize:11,color:"#aeb4c0",margin:"14px 0 6px"}}>ADMIN PASSKEY</label><input autoComplete="current-password" type="password" required value={passkey} onChange={e=>setPasskey(e.target.value)} style={field}/>{error&&<p role="alert" style={{color:"#e99ba4",fontSize:12}}>{error}</p>}<button disabled={busy} style={{...btn,width:"100%",marginTop:12,background:"#d8c49a",color:"#17140e",borderColor:"#d8c49a"}}>{busy?<LoaderCircle size={15}/>:<ShieldCheck size={15}/>} Sign in</button><a href="/message" style={{display:"block",marginTop:16,color:"#858d9d",fontSize:11}}>← Discord custom message</a></form></main>;
 return <main style={shell}><div style={{maxWidth:1120,margin:"0 auto"}}><header style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,flexWrap:"wrap",marginBottom:24}}><div style={{display:"flex",gap:12,alignItems:"center"}}><span style={{display:"grid",placeItems:"center",width:44,height:44,borderRadius:13,background:"#242036",color:"#c6b5ff"}}><Gift size={22}/></span><div><small style={{color:"#9d8bd6",fontWeight:850,letterSpacing:".13em"}}>KINGSHOT OPERATIONS</small><h1 style={{fontSize:"clamp(23px,4vw,32px)",letterSpacing:"-.04em",margin:"3px 0"}}>Gift code control</h1><p style={{margin:0,color:"#7f8795",fontSize:12}}>Active pool, manual corrections and worker controls</p></div></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><button style={btn} disabled={busy} onClick={()=>load()}><RefreshCw size={14}/> Refresh</button><button style={btn} onClick={()=>run("LOGOUT")}><LogOut size={14}/> Sign out</button></div></header>
 {error&&<div role="alert" style={{...panel,borderColor:"#6b343e",color:"#f0a5ad",marginBottom:12}}><AlertTriangle size={15} style={{verticalAlign:"middle",marginRight:8}}/>{error}</div>}{notice&&<div role="status" style={{...panel,borderColor:"#315440",color:"#a5d5b1",marginBottom:12,overflowWrap:"anywhere"}}>{notice}</div>}
 <section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(145px,1fr))",gap:10,marginBottom:16}}><div style={panel}><small style={{color:"#7c8493"}}>TOTAL STORED</small><div style={{fontSize:27,fontWeight:850,marginTop:5}}>{codes.length}</div></div><div style={panel}><small style={{color:"#7c8493"}}>ACTIVE & UNEXPIRED</small><div style={{fontSize:27,fontWeight:850,color:"#91cda1",marginTop:5}}>{activeCount}</div></div><div style={panel}><small style={{color:"#7c8493"}}>INACTIVE / EXPIRED</small><div style={{fontSize:27,fontWeight:850,color:"#d2ad72",marginTop:5}}>{codes.length-activeCount}</div></div></section>
 <section style={{...panel,marginBottom:16}}><h2 style={{fontSize:15,margin:"0 0 13px",display:"flex",alignItems:"center",gap:8}}><Plus size={16}/> Add or restore a code</h2><form onSubmit={e=>{e.preventDefault();run("GIFT_CODE_ADD",{code,expiresAt:expires?new Date(expires).toISOString():null})}} style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(190px,1fr))",gap:10,alignItems:"end"}}><label style={{fontSize:11,color:"#aeb4c0"}}>Gift code<input required minLength={4} maxLength={64} value={code} onChange={e=>setCode(e.target.value.trim())} placeholder="e.g. Hangul2026" autoCapitalize="none" autoComplete="off" style={{...field,display:"block",marginTop:6}}/></label><label style={{fontSize:11,color:"#aeb4c0"}}>Expiry (optional)<input type="datetime-local" value={expires} onChange={e=>setExpires(e.target.value)} style={{...field,display:"block",marginTop:6}}/></label><button disabled={busy} style={{...btn,background:"#d8c49a",color:"#17140e",borderColor:"#d8c49a"}}><Plus size={14}/> Add / reactivate</button></form><p style={{fontSize:10,color:"#727a89",lineHeight:1.5,margin:"10px 0 0"}}>Case is preserved. Adding an existing code reactivates its row rather than creating a duplicate.</p></section>
 <section style={{...panel,marginBottom:16}}><h2 style={{fontSize:15,margin:"0 0 12px"}}>Manual operations</h2><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><button style={btn} disabled={busy} onClick={()=>run("TRIGGER_KINGDOM_VALIDATION")}><Activity size={14}/> Validate all kingdoms</button><button style={btn} disabled={busy} onClick={()=>run("WAKE_REDEEM_WORKERS")}><RotateCcw size={14}/> Run auto-redeem now</button></div><p style={{fontSize:10,color:"#727a89",lineHeight:1.5,margin:"10px 0 0"}}>Kingdom validation uses a global worker lock and does not redeem codes. Auto-redeem runs the existing coordinator and lock safeguards.</p></section>
 <section style={panel}><div style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:12,flexWrap:"wrap",marginBottom:12}}><h2 style={{fontSize:15,margin:0}}>Stored gift codes</h2><div style={{display:"flex",gap:6}}>{[["all","All"],["active","Active"],["inactive","Inactive"]].map(([v,label])=><button key={v} onClick={()=>setFilter(v)} style={{...btn,minHeight:30,padding:"6px 9px",fontSize:10,background:filter===v?"#29243b":"#11151c",borderColor:filter===v?"#51436f":"#303744"}}>{label}</button>)}</div></div>
 {busy&&!codes.length?<p style={{color:"#8b93a2"}}>Loading gift codes…</p>:!visible.length?<p style={{color:"#858d9b",fontSize:12}}>No codes in this view.</p>:<div style={{display:"grid",gap:8}}>{visible.map(item=>{const expired=Boolean(item.expires_at&&Date.parse(item.expires_at)<=Date.now()),effective=Boolean(item.active&&!expired);return <article key={item.id||item.code} style={{display:"grid",gridTemplateColumns:"minmax(0,1fr) auto",gap:10,alignItems:"center",padding:"12px 0",borderTop:"1px solid #252a34"}}><div style={{minWidth:0}}><div style={{display:"flex",gap:8,alignItems:"center",flexWrap:"wrap"}}><b style={{fontSize:13,overflowWrap:"anywhere"}}>{item.code}</b><span style={{fontSize:9,fontWeight:850,padding:"4px 6px",borderRadius:999,background:effective?"#12261b":"#2a2014",color:effective?"#91cda1":"#d2ad72"}}>{effective?"ACTIVE":expired?"EXPIRED":"INACTIVE"}</span>{item.admin_added&&<span style={{fontSize:9,color:"#b5a1ec"}}>MANUAL</span>}</div><div style={{fontSize:10,color:"#737b89",marginTop:5}}>Expires: {date(item.expires_at)} · Seen: {date(item.last_seen_at||item.first_seen_at)}</div></div><div style={{display:"flex",gap:6,flexWrap:"wrap",justifyContent:"flex-end"}}><button title={effective?"Mark inactive":"Activate code"} aria-label={effective?"Mark inactive":"Activate code"} style={btn} disabled={busy} onClick={()=>run("GIFT_CODE_UPDATE",{code:item.code,active:!effective,expiresAt:effective?new Date().toISOString():null})}>{effective?<Clock size={13}/>:<CheckCircle size={13}/>}<span style={{fontSize:10}}>{effective?"Mark expired":"Reactivate"}</span></button><button title="Remove from active pool" aria-label={"Remove "+item.code} style={{...btn,color:"#e99ba4"}} disabled={busy||!item.active} onClick={()=>{if(window.confirm("Remove "+item.code+" from the active redemption pool?"))run("GIFT_CODE_DELETE",{code:item.code})}}><Trash2 size={13}/></button></div></article>})}</div>}</section>
 <footer style={{display:"flex",justifyContent:"space-between",gap:10,flexWrap:"wrap",marginTop:18,color:"#555d6b",fontSize:10}}><span><ShieldCheck size={12} style={{verticalAlign:"middle",marginRight:5}}/>Admin actions are server-authenticated and rate-limited.</span><a href="/message" style={{color:"#9d8bd6"}}>Discord custom message ↗</a></footer></div></main>;
}
