create table if not exists public.kingshot_push_subscriptions (id bigint generated by default as identity primary key, endpoint text not null unique, p256dh text not null, auth text not null, created_at timestamptz not null default now(), last_seen_at timestamptz not null default now());
alter table public.kingshot_push_subscriptions enable row level security;
revoke all on public.kingshot_push_subscriptions from public, anon, authenticated;
grant all on public.kingshot_push_subscriptions to service_role;
